### ISSUE TITLE
Rendering failure?

### ISSUE THREAD

**Issue by Ahacad** [micromark/micromark-extension-directive#15]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.1

### Steps to reproduce

1. init a new npm repo
2. install dependencies: `micromark` and `micromark-extension-directive`
3. create a JavaScript file say `index.js`, put the example code from README here:
```javascript
import fs from 'node:fs'
import {micromark} from 'micromark'
import {directive, directiveHtml} from 'micromark-extension-directive'

const output = micromark(fs.readFileSync('example.md'), {
  extensions: [directive()],
  htmlExtensions: [directiveHtml({abbr})]
})

console.log(output)

function abbr(d) {
  if (d.type !== 'textDirective') return false

  this.tag('<abbr')

  if (d.attributes && 'title' in d.attributes) {
    this.tag(' title="' + this.encode(d.attributes.title) + '"')
  }

  this.tag('>')
  this.raw(d.label || '')
  this.tag('</abbr>')
}
```
4. inside `example.md`, input all the text from the SYNTAX section in README
5. run `node index.js` and get output in the console

### Expected behavior

Directives in blocks and containers should get rendered, but the output is an empty string.

### Actual behavior

Below is the actual output:
```
<p>Directives in text can form with a single colon, such as .
Their syntax is <code>:name[label]{attributes}</code>.</p>
<p>Leafs (block without content) can form by using two colons:</p>
<p>Their syntax is <code>::name[label]{attributes}</code> on its own line.</p>
<p>Containers (blocks with content) can form by using three colons:</p>
<p>The <code>name</code> part is required.  The first character must be a letter, other
characters can be alphanumerical, <code>-</code>, and <code>_</code>.
<code>-</code> or <code>_</code> cannot end a name.</p>
<p>The <code>[label]</code> part is optional (<code>:x</code> and <code>:x[]</code> are equivalent)†.
When used, it can include text constructs such as emphasis and so on: <code>x[a *b* c]</code>.</p>
<p>The <code>{attributes}</code> part is optional (<code>:x</code> and <code>:x{}</code> are equivalent)†.
When used, it is handled like HTML attributes, such as that <code>{a}</code>, <code>{a=&quot;&quot;}</code>,
, <code>{a=''}</code> but also <code>{a=b}</code>, <code>{a=&quot;b&quot;}</code>, and <code>{a='b'}</code> are equivalent.
Shortcuts are available for <code>id=</code> (<code>{#readme}</code> for <code>{id=readme}</code>) and
<code>class</code> (<code>{.big}</code> for <code>{class=big}</code>).
When multiple ids are found, the last is used; when multiple classes are found,
they are combined: <code>{.red class=green .blue}</code> is equivalent to
<code>{.red .green .blue}</code> and <code>{class=&quot;red green blue&quot;}</code>.</p>
<p>† there is one case where a name must be followed by an empty label or empty
attributes: a <em>text</em> directive that only has a name, cannot be followed by a
colon. So, <code>:red:</code> doesn’t work. Use either <code>:red[]</code> or <code>:red{}</code> instead.
The reason for this is to allow GitHub emoji (gemoji) and directives to coexist.</p>
<p>Containers can be nested by using more colons outside:</p>
<p>The closing fence must include the same or more colons as the opening.
If no closing is found, the container runs to the end of its parent container
(block quote, list item, document, or other container).</p>
```

You can see containers and blocks are omitted, by my memory they should have got rendered.

### Runtime

Node v14

### Package manager

npm v7

### OS

Linux

**Comment by wooorm** [comment]
Hey!

I think the idea here is that unknown directives are ignored by default. As they could be turned into anything: dangerous html, youtube videos, embed of other stuff, math, you name it.
Just rendering something is probably not the best outcome.

So, the example JS code works with the example MD code, but not with the syntax explanation. That requires more code.

Does that make sense?

**Comment by Ahacad** [comment]
Oh, I am clear about it now. So it requires similar code like: 
```javascript
function abbr(d) {
  if (d.type !== 'textDirective') return false

  this.tag('<abbr')

  if (d.attributes && 'title' in d.attributes) {
    this.tag(' title="' + this.encode(d.attributes.title) + '"')
  }

  this.tag('>')
  this.raw(d.label || '')
  this.tag('</abbr>')
}
```
to render the containers and blocks right?

**Comment by wooorm** [comment]
Yes, you need to write your own handlers to deal with containers in the way you want!

**Comment by wooorm** [comment]
closing as it’s more a question that doesn’t need any code changes!
