### ISSUE TITLE
Ignore colon in words

### ISSUE THREAD

**Issue by fhilgers** [micromark/micromark-extension-directive#26]
### Initial checklist

- [X] I read the [support docs](https://github.com/micromark/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/micromark/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/micromark/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Amicromark&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The german language has different forms of words depending on the gender (example: `Mitglieder` male, `Mitgliederinnen` female). One modern variant of writing those, which is required in some formal contexts, is `Mitglieder:innen` with a colon separating the suffix. Currently this leads to unwanted directives.

### Solution

I could not find a test, which explictly tests for a textDirective directly following a word. The only ones I could find was a textDirective directly after an opening bracket, which is essentially the start of a span and not after a letter.

I cannot think of a usecase, where one would want to have a textDirective, directly attached to a word. Also there are already strict requirements for the leafDirectives and containerDirectives to be directly at the start of a line. Also, all directives have to directly follow the colons with no space.

What is the reason for allowing textDirectives directly attached to a word? If there is none, I would like to require that a textDirective is not allowed when attached to a word.

### Alternatives

- A whitelist when handling directives which ignores the unwanted directives.
- Escaping all uses of colons inside words.

**Comment by ChristianMurphy** [comment]
Welcome @fhilgers! 👋 
Pretty much all markdown inline constructs can happen mid word

---

```md
example*example*
example**example**
example`example`
```

example*example*
example**example**
example`example`

---

And any of these can be escaped by adding a backslash `\`.
I don't see a reason why this construct should be different from all the others.

**Comment by fhilgers** [comment]
Woops, that makes sense. In my mind the directive syntax felt so much like a function call from general programming languages that I found that behaviour weird. But you're definetly right!
