### ISSUE TITLE
Container directive does not properly contain all contents when attributes are specified.

### ISSUE THREAD

**Issue by Corvimae** [micromark/micromark-extension-directive#4]
### Subject of the issue

I have a container directive that takes an optional argument `theme`. When I put a list inside the container, it is rendered within the container if there are no attribute braces and outside the container if there are braces and the closing ::: is rendered as text.

### Your environment

*   **OS**: macOS Big Sur
*   **Packages**:
 ```
├─ micromark-extension-directive@1.1.1
│  ├─ micromark@~2.11.0
```
*   **Env**: node `v15.5.0`, yarn `1.22.5`

### Steps to reproduce

**Without attribute braces:**
```
:::card
**Test Content**

- This
- Is
- A
- List
:::
```

<img width="824" alt="image" src="https://user-images.githubusercontent.com/236379/103491177-2b0d2d00-4de7-11eb-808b-197063b0a980.png">

**With attribute braces:**
```
:::card{}
**Test Content**

- This
- Is
- A
- List
:::
```
<img width="828" alt="image" src="https://user-images.githubusercontent.com/236379/103491165-1335a900-4de7-11eb-82b1-21ad1ad3de93.png">

### Expected behavior

Both cards should render the same children.

### Actual behavior

The card with attributes does not contain the list, and the closing ::: is rendered as text.

**Comment by wooorm** [comment]
Thanks, released! https://github.com/micromark/micromark-extension-directive/releases/tag/1.1.2
